### ISSUE TITLE
Request is cancelled on Mac Catalyst

### ISSUE THREAD

**Issue by anonrig** [onurhuseyincantay/Hover#2]
Here's the response:

```
 Task <31B06E42-1D6F-42C2-84A8-65CB0BEE175F>.<1> finished with error [-999] Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://api.notemate.com/notemate/register, NSLocalizedDescription=cancelled, NSErrorFailingURLKey=https://api.notemate.com/notemate/register}
```

**Comment by onurhuseyincantay** [comment]
As I see this problem is only happening when you do a sink or assign which is inside your project not in the framework cause the framework has 2 options the first one is making a request with subscriber or the second one is making a request without a subscriber but it returns a publisher so you can sink the value so whenever you use assign or sink these generic classes conforms to AnyCancellable Protocol which makes you able to assign it to a local variable so the arc doesn't deallocate the memory so the call is not interrupted meanwhile you are sinking.
